export const productsList = [
  { product: "Eier", unit: "" },
  { product: "Mehl", unit: "g" },
  { product: "Zucker", unit: "g" },
  { product: "Butter", unit: "g" },
  { product: "Milch", unit: "ml" },
  { product: "Milch 3,5%", unit: "ml" },
  { product: "Milch 1,5%", unit: "ml" },
  { product: "Hafermilch", unit: "ml" },
  { product: "Kokosmilch", unit: "ml" },
  { product: "Kokosmilch 0%", unit: "ml" },
  { product: "Sojamilch", unit: "ml" },
  { product: "Mandelmilch", unit: "ml" },

  { product: "Salz", unit: "g" },
  { product: "Prise Salz", unit: "" },
  { product: "Pfeffer", unit: "" },
  { product: "Prise Pfeffer", unit: "" },
  { product: "Gewürze", unit: "" },

  { product: "Zwiebeln", unit: "g" },
  { product: "Frühlingszw.", unit: "g" },
  { product: "Schalotten", unit: "g" },
  { product: "Rote Zwiebeln", unit: "g" },
  { product: "Knoblauch", unit: "g" },

  { product: "Paprika", unit: "g" },
  { product: "Rote Paprika", unit: "g" },
  { product: "Grüne Paprika", unit: "g" },
  { product: "Gelbe Paprika", unit: "g" },

  { product: "Olivenöl", unit: "g" },
  { product: "Bratöl", unit: "g" },
  { product: "Sonnenblumenöl", unit: "g" },
  { product: "Kürbiskernöl", unit: "g" },

  { product: "Reis", unit: "g" },
  { product: "Basmati Reis", unit: "g" },
  { product: "Jasmin Reis", unit: "g" },
  { product: "Wildreis", unit: "g" },
  { product: "Langkorn Reis", unit: "g" },
  { product: "Sushi Reis", unit: "g" },

  { product: "Nudeln", unit: "g" },
  { product: "Vollkornnudeln", unit: "g" },

  { product: "Kartoffeln", unit: "g" },
  { product: "Rote Kartoffeln", unit: "g" },
  { product: "Spargel", unit: "g" },
  { product: "Grüner Spargel", unit: "g" },
  { product: "Karotten", unit: "g" },
  { product: "Gurke", unit: "g" },
  { product: "Aubergine", unit: "g" },

  { product: "Weißkohl", unit: "g" },
  { product: "Petersilie", unit: "g" },
  { product: "Koriander", unit: "g" },
  { product: "Schnittlauch", unit: "g" },
  { product: "Chilliflocken", unit: "g" },
  { product: "Sriracha-Sauce", unit: "g" },

  { product: "Organge", unit: "g" },
  { product: "Eisbergsalat", unit: "g" },
  { product: "Feldsalat", unit: "g" },
  { product: "Apfel", unit: "g" },
  { product: "Birne", unit: "g" },
  { product: "Zucchini", unit: "g" },
  { product: "Kürbis", unit: "g" },
  { product: "Weintrauben", unit: "g" },
  { product: "Müsli", unit: "g" },
  { product: "Haferflocken", unit: "g" },
  { product: "Brötchen", unit: "" },
  { product: "Brot", unit: "g" },
  { product: "Kaffee", unit: "g" },

  { product: "Tee", unit: "g" },
  { product: "Grüner Tee", unit: "g" },
  { product: "Schwarzer Tee", unit: "g" },

  { product: "Schweinefleisch", unit: "g" },
  { product: "Rindfleisch", unit: "g" },
  { product: "Hähnchenfleisch", unit: "g" },
  { product: "Normaler Tofu", unit: "g" },
  { product: "Geräucherter Tofu", unit: "g" },
  { product: "Seitan", unit: "g" },
  { product: "Käse", unit: "g" },
  { product: "Streukäse", unit: "g" },
  { product: "Mozarellabälle", unit: "" },
  { product: "Cheddar", unit: "g" },

  { product: "Quark", unit: "g" },
  { product: "Quark 20%", unit: "g" },
  { product: "Quark 40%", unit: "g" },
  { product: "Frischkäse 0%", unit: "g" },
  { product: "Frischkäse", unit: "g" },
  { product: "Veganer Frischkäse", unit: "g" },

  { product: "Parmesan", unit: "g" },
  { product: "Schlagsahne", unit: "g" },
  { product: "Margarine", unit: "g" },
  { product: "Margarine", unit: "g" },
  { product: "Vegane Butter", unit: "g" },
  { product: "Vegane Würste", unit: "g" },
  { product: "Veganer Aufschnitt", unit: "g" },
  { product: "Schmelzkäse", unit: "g" },
  { product: "Veganes Gehacktes", unit: "g" },
  { product: "Gehacktes", unit: "g" },
  { product: "Schmand", unit: "g" },
  { product: "Saure Sahne", unit: "g" },
  { product: "Veganer Joghurt", unit: "g" },
  { product: "Joghurt", unit: "g" },
  { product: "Gewürzgurken", unit: "g" },
  { product: "Sojasauce", unit: "g" },
  { product: "Reisessig", unit: "g" },
  { product: "Noriblatt", unit: "" },
  { product: "Gemüsebrühe", unit: "ml" },
  { product: "Rinderbrühe", unit: "ml" },
  { product: "Ramen", unit: "g" },
  { product: "Kekse", unit: "g" },
  { product: "Dunkle Schokolade", unit: "g" },
  { product: "Helle Schokolade", unit: "g" },
  { product: "Schokolade", unit: "g" },
  { product: "Gummibärchen", unit: "g" },
  { product: "Chips", unit: "g" },

  { product: "Schnitzel", unit: "" },
  { product: "Vegane Schnitzel", unit: "" },
  { product: "Steak", unit: "" },
  { product: "Veganes Steak", unit: "" },

  { product: "Vanille", unit: "g" },
  { product: "Vanillezucker", unit: "g" },

  { product: "Trockene Hefe", unit: "g" },
  { product: "Frische Hefe", unit: "g" },

  { product: "Avocado", unit: "" },

  { product: "Backpulver", unit: "g" },
  { product: "Gehackte Mandeln", unit: "g" },
  { product: "Gehackte Haselnüsse", unit: "g" },
  { product: "Walnüsse", unit: "g" },
  { product: "Mandeln", unit: "g" },
  { product: "Mandelsplitter", unit: "g" },
  { product: "Haselnüsse", unit: "g" },
  { product: "Rosinen", unit: "g" },

  { product: "Maiswaffeln", unit: "" },
  { product: "Burger Brötchen", unit: "" },
  { product: "Brioche Brötchen", unit: "" },

  { product: "Marzipan", unit: "g" },

  { product: "Pilze", unit: "g" },
  { product: "Champingnons", unit: "g" },
  { product: "Shiitake", unit: "g" },
  { product: "Steinpilze", unit: "g" },
  { product: "Austernpilze", unit: "g" },
  { product: "Pfifferlinge", unit: "g" },

  { product: "Senf", unit: "g" },
  { product: "Ketchup", unit: "g" },

  { product: "Sauce Hollandaise", unit: "ml" },
  { product: "Bratensauce", unit: "ml" },
  { product: "Helle Bratensauce", unit: "ml" },

  { product: "Forelle", unit: "g" },
  { product: "Lachs", unit: "g" },

  { product: "Heidelbeeren", unit: "g" },
  { product: "Himbeeren", unit: "g" },
  { product: "Kirschen", unit: "g" },
  { product: "Mango", unit: "g" },
  { product: "Erdbeeren", unit: "g" },
  { product: "Wildfrüchte", unit: "g" },

  { product: "Honig", unit: "ml" },
  { product: "Agavendicksaft", unit: "ml" },
  { product: "Bacon", unit: "g" },
  { product: "Veganer Bacon", unit: "g" },
  { product: "Toastscheiben", unit: "" },

  { product: "Linsen", unit: "g" },
  { product: "Kichererbsen", unit: "g" },
  { product: "Kidneybohnen", unit: "g" },
  { product: "Grünes Pesto", unit: "g" },
  { product: "Rotes Pesto", unit: "g" },
  { product: "Pesto", unit: "g" },
  { product: "Walnuss-Ricotta-Pesto", unit: "g" },

  { product: "Mais", unit: "g" },
  { product: "Ananas", unit: "g" },
  { product: "Passierte Tomaten", unit: "ml" },
  { product: "Tomatenmark", unit: "g" },
  { product: "Mayonnaise", unit: "ml" },
  { product: "Paniermehl", unit: "ml" },

  { product: "Weißwein", unit: "ml" },
  { product: "Rotwein", unit: "ml" },
  { product: "Bier", unit: "ml" },
  { product: "Sojagranulat", unit: "g" },
  { product: "Gnocchi", unit: "g" },
  { product: "Schupfnudeln", unit: "g" },
  { product: "Tomaten", unit: "g" },
  { product: "Kirschtomaten", unit: "g" },
  { product: "Fleischtomaten", unit: "g" },
  { product: "Frikassee", unit: "g" },
  { product: "Quinoa", unit: "g" },
  { product: "Leinsamen", unit: "g" },
  { product: "Spinat", unit: "g" },
  { product: "Blattspinat", unit: "g" },
  { product: "Rahmspinat", unit: "g" },

  { product: "Kräuter", unit: "g" },
];
