export const productsList = [
  { product: "eggs", unit: "" },
  { product: "flour", unit: "g" },
  { product: "sugar", unit: "g" },
  { product: "butter", unit: "g" },
  { product: "milk", unit: "ml" },
  { product: "salt", unit: "g" },
  { product: "pepper", unit: "g" },
  { product: "onion", unit: "" },
  { product: "garlic", unit: "cloves" },
  { product: "olive oil", unit: "ml" },
  { product: "rice", unit: "g" },
  { product: "pasta", unit: "g" },
  { product: "chicken breast", unit: "g" },
  { product: "beef", unit: "g" },
  { product: "tomatoes", unit: "" },
  { product: "potatoes", unit: "g" },
  { product: "carrots", unit: "g" },
  { product: "bell pepper", unit: "" },
  { product: "lettuce", unit: "g" },
  { product: "cheese", unit: "g" },
  { product: "bread", unit: "slices" },
  { product: "yogurt", unit: "g" },
  { product: "lemon", unit: "" },
  { product: "bacon", unit: "g" },
  { product: "chocolate", unit: "g" },
  { product: "vanilla extract", unit: "ml" },
  { product: "honey", unit: "ml" },
  { product: "baking powder", unit: "g" },
  { product: "cinnamon", unit: "g" },
  { product: "nutmeg", unit: "g" },
  { product: "coconut oil", unit: "ml" },
  { product: "soy sauce", unit: "ml" },
  { product: "vinegar", unit: "ml" },
  { product: "mustard", unit: "g" },
  { product: "mayonnaise", unit: "g" },
  { product: "ketchup", unit: "ml" },
  { product: "black beans", unit: "g" },
  { product: "corn", unit: "g" },
  { product: "avocado", unit: "" },
  { product: "shrimp", unit: "g" },
  { product: "salmon fillet", unit: "g" },
  { product: "ground beef", unit: "g" },
  { product: "sausage", unit: "" },
  { product: "mushrooms", unit: "g" },
  { product: "spinach", unit: "g" },
  { product: "cucumber", unit: "" },
  { product: "sour cream", unit: "g" },
  { product: "cream cheese", unit: "g" },
  { product: "oats", unit: "g" },
  { product: "nuts", unit: "g" },
  { product: "raisins", unit: "g" },
  { product: "balsamic vinegar", unit: "ml" },
  { product: "red wine vinegar", unit: "ml" },
  { product: "maple syrup", unit: "ml" },
  { product: "walnuts", unit: "g" },
  { product: "almonds", unit: "g" },
  { product: "pecans", unit: "g" },
  { product: "sunflower seeds", unit: "g" },
  { product: "pumpkin seeds", unit: "g" },
  { product: "sesame seeds", unit: "g" },
  { product: "cocoa powder", unit: "g" },
  { product: "coconut milk", unit: "ml" },
  { product: "green beans", unit: "g" },
  { product: "peas", unit: "g" },
  { product: "chickpeas", unit: "g" },
  { product: "lentils", unit: "g" },
  { product: "quinoa", unit: "g" },
  { product: "ground turkey", unit: "g" },
  { product: "tofu", unit: "g" },
  { product: "cornmeal", unit: "g" },
  { product: "breadcrumbs", unit: "g" },
  { product: "salsa", unit: "ml" },
  { product: "tortillas", unit: "" },
  { product: "hummus", unit: "g" },
  { product: "greek yogurt", unit: "g" },
  { product: "coconut flakes", unit: "g" },
  { product: "nutritional yeast", unit: "g" },
  { product: "cottage cheese", unit: "g" },
  { product: "cheddar cheese", unit: "g" },
  { product: "parmesan cheese", unit: "g" },
  { product: "mozzarella cheese", unit: "g" },
  { product: "feta cheese", unit: "g" },
  { product: "blue cheese", unit: "g" },
  { product: "cheddar cheese", unit: "g" },
  { product: "sour cream", unit: "g" },
  { product: "cream cheese", unit: "g" },
  { product: "cottage cheese", unit: "g" },
  { product: "sour cream", unit: "g" },
  { product: "cream cheese", unit: "g" },
  { product: "cottage cheese", unit: "g" },
];
